use baseball;

drop table if exists BattingStats;
drop table if exists PitchingStats;


create table BattingStats (
    StatsID int identity(1, 1),
    Year    int,
    Team    nvarchar(30),
    Player  nvarchar(150),
    Age     int,
    Pos     nvarchar(15),
    WAR     float,
    G       int,
    PA      int,
    AB      int,
    R       int,
    H       int,
    [2B]    int,
    [3B]    int,
    HR      int,
    RBI     int,
    SB      int,
    CS      int,
    BB      int,
    SO      int,
    BA      decimal(4, 3),
    OBP     decimal(4, 3),
    SLG     decimal(4, 3),
    OPS     decimal(4, 3),
    [OPS+]  int,
    rOBA    decimal(4, 3),
    [Rbat+] int,
    TB      int,
    GIDP    int,
    HBP     int,
    SH      int,
    SF      int,
    IBB     int,

    constraint PK_BattingStats primary key (StatsID)
);

create table PitchingStats(
	StatsID int identity(1, 1),
	Year    int,
	Team    nvarchar(30),
	Player  nvarchar(150),
	Age     int,
	Pos     nvarchar(15),
	WAR     float,
	W       int,
	L       int,
	[W-L%]  decimal(4, 3),
	ERA     float,
	G       int,
	GS      int,
	GF      int,
	CG      int,
	SHO     int,
	SV      int,
	IP      float,
	H       int,
	R       int,
	ER      int,
	HR      int,
	BB      int,
	IBB     int,
	SO      int,
	HBP     int,
	BK      int,
	WP      int,
	BF      int,
	[ERA+]  int,
	FIP     float,
	WHIP    float,
	H9      float,
	HR9     float,
	BB9     float,
	SO9     float,
	[SO/BB] float,

	constraint PK_PitchingStats primary key (StatsID)
);